// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuFPj4m-jerhjcnYYKpx31rPLS4uN2HtQ',
    appId: '1:21657283465:web:adff85425a890ca3a38f58',
    messagingSenderId: '21657283465',
    projectId: 'flutterauthfirebasee',
    authDomain: 'flutterauthfirebasee.firebaseapp.com',
    storageBucket: 'flutterauthfirebasee.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFF7g085W2ZtkTzAnVF8hP1Hnrt_9FsR0',
    appId: '1:21657283465:android:393715279b1ec053a38f58',
    messagingSenderId: '21657283465',
    projectId: 'flutterauthfirebasee',
    storageBucket: 'flutterauthfirebasee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzaZpSL4WO3CMQGMK3cCfTmURETWRvFHY',
    appId: '1:21657283465:ios:5871d658ab482998a38f58',
    messagingSenderId: '21657283465',
    projectId: 'flutterauthfirebasee',
    storageBucket: 'flutterauthfirebasee.appspot.com',
    iosBundleId: 'com.example.testfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzaZpSL4WO3CMQGMK3cCfTmURETWRvFHY',
    appId: '1:21657283465:ios:2deeb6632ea4a738a38f58',
    messagingSenderId: '21657283465',
    projectId: 'flutterauthfirebasee',
    storageBucket: 'flutterauthfirebasee.appspot.com',
    iosBundleId: 'com.example.testfirebase.RunnerTests',
  );
}
